services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ..:/workspaces/competition-schedule-live:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: live_competition_group_tracker
    volumes:
      - mocks-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d live_competition_group_tracker"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  mocks-postgres:
